[[redirects]]
  from = "/main//główna/*"
  to = "/main"
  status = 301
  force = true

[[redirects]]
  from = "/main//główna"
  to = "/main"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200