[[redirects]]
  from = "/main//główna"
  to = "/"
  status = 301

[[redirects]]
  from = "/test"
  to = "/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
